parsers:
  headers:
    User-Agent: "Mozilla/5.0 (compatible; MyParser/1.0)"

websites:
  MMCS:
    base_url: "https://mmcs.sfedu.ru"
    pages:
      data:
        - name: general_info
          path: "/toabitur"
          selectors:
            info: "div.article-content"
            contacts: "div.yjsquare_in address"
        - name: history
          path: "/2014-12-10-12-02-39/greatpatrioticwar"
          selectors:
            history: "div.newsitem_text"
        - name: masters_degree
          path: "/%D0%BC%D0%B0%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%B0"
          selectors:
            masters_degree: "div.news_item_a"
      news:
        - name: news_page_1
          path: "/?start=0"
          container: "div.yjsg-newsitems"
          item_selector: "div.news_item_f"
          selectors:
            title: "h2.article_title"
            date: "div.newsitem_info span.createdate"
            author: "div.newsitem_info span.createby"
            text: "div.newsitem_text"
            link:
              selector: "a.btn"
              attribute: "href"
        - name: news_page_2
          path: "/?start=9"
          container: "div.yjsg-newsitems"
          item_selector: "div.news_item_f"
          selectors:
            title: "h2.article_title"
            date: "div.newsitem_info span.createdate"
            author: "div.newsitem_info span.createby"
            text: "div.newsitem_text"
            link:
              selector: "a.btn"
              attribute: "href"

  SFEDU:
    base_url: "https://sfedu.ru"
    pages:
      data:
        - name: general_info
          path: "/www/stat_pages22.show?p=UNI/N11897/P"
          selectors:
            info: "div#ideologiya1"
        - name: history
          path: "/www/stat_pages22.show?p=HIS/main/M"
          selectors:
            history: "div.content"
        - name: education
          path: "/www/stat_pages22.show?p=EDU/N12080/P"
          selectors:
            education: "article.left_side_column"
        - name: week_of_academic_mobility
          path: "/www/stat_pages22.show?p=NAM/main/M"
          selectors:
            week_of_academic_mobility: "article.left_col"
      news:
        - name: news_page_1
          path: "/press-center/newspage/1"
          container: "div#Dcont"
          item_selector: "div.act"
          selectors:
            title:
              selector: "div.acttitle a"
              attribute: "text"
            date: "div.actdate"
            text: "div.acttext"
            link:
              selector: "div.acttitle a"
              attribute: "href"
            image:
              selector: "div.actfoto img"
              attribute: "src"
        - name: news_page_2
          path: "/press-center/newspage/2"
          container: "div#Dcont"
          item_selector: "div.act"
          selectors:
            title:
              selector: "div.acttitle a"
              attribute: "text"
            date: "div.actdate"
            text: "div.acttext"
            link:
              selector: "div.acttitle a"
              attribute: "href"
            image:
              selector: "div.actfoto img"
              attribute: "src"

  MMCS_schedule:
    base_url: "https://schedule.sfedu.ru/APIv1/schedule/grade/"